export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_PRODUCT_DOWNLOAD = 'START_PRODUCT_DOWNLOAD';
export const DOWNLOAD_SUCCESSFUL_PRODUCT = 'DOWNLOAD_SUCCESSFUL_PRODUCT';
export const DOWNLOAD_PRODUCT_ERROR = 'DOWNLOAD_PRODUCT_ERROR';